function problem_1()
{
    description = [
        "https://projecteuler.net/problem=1",
        "If we list all the natural numbers below 10 that are multiples of 3 or 5,",
        "we get 3, 5, 6 and 9. The sum of these multiples is 23.",
        "",
        "Find the sum of all the multiples of 3 or 5 below 1000. ",
    ];

    console.log(description.join("\n"));

    let N = Math.round(999 / 3)
    let Q = Math.round(999 / 5)
    let R = Math.round(999 / 15)
    let _3sum = (N * (N + 1)) / 2
    let _5sum = (Q * (Q + 1)) / 2
    let _15sum = (R * (R + 1)) / 2
    return 3 * _3sum + 5 * _5sum - 15 * _15sum
}

function problem_2()
{
    description = [
        "https://projecteuler.net/problem=2",
        "Each new term in the Fibonacci sequence is generated by adding the previous two terms.",
        "By starting with 1 and 2, the first 10 terms will be",
        "",
        "\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...",
        "",
        "By considering the terms in the Fibonacci sequence whose values do not exceed four million,",
        "find the sum of the even-valued terms."
    ];

    console.log(description.join("\n"));

    let a = 0
    let b = 1
    let sum = 0
    while (b < 4e6)
    {
        if (b % 2 === 0)
        {
            sum += b;
        }
        let c = b + a;
        a = b;
        b = c;
    }
    return sum;
}

problems = [problem_1, problem_2]

problems.forEach((runnable) => console.log(`result: ${runnable()}`));