# https://stackoverflow.com/a/60956561/5217293
def register_problem(f):
    """
    Creates an attribute on the method, so it can
    be identied as a function to call
    """
    f._is_problem = True
    return f

def current(f):
    """
    Creates an attribute on the method, so it can
    be identied as a function to call
    """
    f._is_current = True
    return f

class Problems:
    def __init__(self, only_current = False):
        self.problem_methods = {}
        for name in dir(self):
            attr = getattr(self,name)
            if getattr(attr,"_is_problem",False):
                if only_current:
                    if getattr(attr, "_is_current", False):
                        self.problem_methods[name] = attr
                else:
                    self.problem_methods[name] = attr

    def run(self):
        for _,method in self.problem_methods.items():
            print(f"\t{'='*40}")
            print(method.__doc__)
            print(f"\tResult: {method()}")
            print(f"\t{'='*40}")
            print()

    @register_problem
    def __1(self):
        """\thttps://projecteuler.net/problem=1
        If we list all the natural numbers below 10 that are multiples of 3 or 5, 
        we get 3, 5, 6 and 9. The sum of these multiples is 23.

        Find the sum of all the multiples of 3 or 5 below 1000.
        """

        return sum([i for i in range(1000) if i % 3 == 0 or i % 5 == 0])
    
    @current
    @register_problem
    def __2(self):
        """
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million,
        find the sum of the even-valued terms.
        """
        return 0